# For public, HTTPS servers.
version: '2.1'

services:

  postgres:
    volumes:
      - ../kobo-deployments/postgres/master/postgres.conf:/kobo-docker-scripts/master/postgres.conf

  mongo:
    image: kobotoolbox/mongo:latest
    environment:
      - MONGO_DATA=/srv/db
    volumes:
      - ./.vols/mongo:/srv/db
